name: Build

on: 
  push:
      branches:
        - "*"
        - "!main"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: build cache
        uses: actions/cache@v4
        with:
          path: |
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/bun.lockb') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/bun.lockb') }}-

      - name: install packages
        run: bun install --frozen-lock-file

      - name: build project
        run: bun run build
        
      - name: remove packages and install prod dependencies
        run: |
          rm -rf node_modules
          bun install --production --frozen-lock-file
        
      - name: set up docker buildx
        uses: docker/setup-buildx-action@v3
            
      - name: build docker image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          tags: dragon4343/easyflow-frontend:latest
          secrets: |
            "origin_certificate=${{ secrets.ORIGIN_CERTIFICATE }}"
            "origin_key=${{ secrets.ORIGIN_KEY }}"