name: Deploy

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: build cache
        uses: actions/cache@v4
        with:
          path: |
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/bun.lockb') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/bun.lockb') }}-

      - name: install packages
        run: bun install --frozen-lock-file
        
      - name: linting
        run: bun --npm run lint

      - name: build project
        run: bun run build

      - name: remove packages and install prod dependencies
        run: |
          rm -rf node_modules
          bun install --production --frozen-lock-file
  
      - name: login to docker
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: set up docker buildx
        uses: docker/setup-buildx-action@v3
        
      - name: create image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.DOCKER_REGISTRY }}/${{ vars.DOCKER_NAMESPACE }}/${{ vars.DOCKER_IMAGE_NAME }}
            
      - name: build and push docker image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.ouputs.tags[0] }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outpust.annotations }}
          push: true
            
      - name: setup railway cli
        run: npm i -g @railway/cli
      
      - name: trigger redeploy on railway
        run: RAILWAY_TOKEN=${{ secrets.RAILWAY_TOKEN }} railway redeploy -s ${{ vars.RAILWAY_SERVICE_NAME }} -y
